TOPTARGETS := all clean release

UTILSDIR := Utils/.
FIRSTDIR := 

SUBDIRS := $(wildcard */.)
SUBDIRS := $(filter-out LatexUtils/. VS141/. VS/. $(UTILSDIR) $(FIRSTDIR),$(SUBDIRS))

$(TOPTARGETS): $(SUBDIRS)

$(SUBDIRS): $(FIRSTDIR)
	$(MAKE) -C $@ $(MAKECMDGOALS)

$(FIRSTDIR): $(UTILSDIR)
	$(MAKE) -C $@ $(MAKECMDGOALS)

$(UTILSDIR):
	$(MAKE) -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)
.PHONY: $(TOPTARGETS) $(FIRSTDIR)
.PHONY: $(TOPTARGETS) $(UTILSDIR)
